//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_CONFIG
    {
        public int ID { get; set; }
        public string ID_ { get; set; }
        public string HISTORYNAME { get; set; }
        public string SOURCE { get; set; }
        public string SOURCEHANDLE { get; set; }
        public string TIMEZONE { get; set; }
        public string INTERVAL_ { get; set; }
        public string SYSTEMTAGS { get; set; }
        public string VALUEFACETS { get; set; }
        public string TABLE_NAME { get; set; }
        public string DB_TIMEZONE { get; set; }




        public virtual ICollection<AMETEC_POINTS_CONSUMOKWH_CFG0> AMETEC_POINTS_CONSUMOKWH_CFG0 { get; set; }
        public virtual ICollection<AMETEC_POINTS_CONSUMOKWH1_CFG0> AMETEC_POINTS_CONSUMOKWH1_CFG0 { get; set; }
        public virtual ICollection<AMETEC_POINTS_CONSUMOKWH2_CFG0> AMETEC_POINTS_CONSUMOKWH2_CFG0 { get; set; }
        public virtual ICollection<AMETEC_POINTS_CONSUMOKWH3_CFG0> AMETEC_POINTS_CONSUMOKWH3_CFG0 { get; set; }
        public virtual ICollection< AMETEC_SUBMETERING_TOTAL> AMETEC_SUBMETERING_TOTAL { get; set; }
        public virtual ICollection<AMETEC_SUBMETERING_TOTAL1> AMETEC_SUBMETERING_TOTAL1 { get; set; }
        public virtual ICollection< AMETEC_SUBMETERING_TOTAL2> AMETEC_SUBMETERING_TOTAL2 { get; set; }
        public virtual ICollection<AMETEC_SUBMETERING_TOTAL3> AMETEC_SUBMETERING_TOTAL3 { get; set; }
        public virtual ICollection<AMETEC_SUBMETERING_TOTAL5> AMETEC_SUBMETERING_TOTAL5 { get; set; }
        public virtual ICollection<AMETEC_SUBMETERING_TOTALPLANTPOWER> AMETEC_SUBMETERING_TOTALPLANTPOWER { get; set; }
        public virtual ICollection<HISTORYNUMERICTRENDRECORD> HISTORYNUMERICTRENDRECORDs { get; set; }


    }
}
