//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tenant_billing_info
    {
        public int int_id { get; set; }
        public Nullable<int> int_tenant_id { get; set; }
        public Nullable<int> int_template_id { get; set; }
        public Nullable<decimal> dec_rate { get; set; }
        public Nullable<bool> bit_is_seasonal_rate { get; set; }
        public decimal dec_seasonal_multi_rate { get; set; }
        public Nullable<bool> bit_is_surchare { get; set; }
        public Nullable<decimal> dec_surcharge_amt { get; set; }
        public string str_min_billable_over { get; set; }
        public string str_charge_tenant_min { get; set; }
        public string str_charge_tenant_max { get; set; }
        public bool bit_is_consolidate_zone { get; set; }
        public bool bit_is_print { get; set; }
        public bool bit_is_file { get; set; }
        public int int_type { get; set; }
        public string str_email { get; set; }
    
        public virtual tbl_template tbl_template { get; set; }
        public virtual tbl_user_master tbl_user_master { get; set; }
    }
}
