//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_invoice()
        {
            this.tbl_invoice_details = new HashSet<tbl_invoice_details>();
        }
    
        public int int_invoice_id { get; set; }
        public Nullable<System.DateTime> date_invoice_date { get; set; }
        public Nullable<int> int_tenant_id { get; set; }
        public Nullable<bool> bit_tenant_active { get; set; }
        public Nullable<System.DateTime> date_s_bill_date { get; set; }
        public Nullable<System.DateTime> date_e_bill_date { get; set; }
        public Nullable<decimal> dec_total { get; set; }
        public Nullable<decimal> dec_tax_amt { get; set; }
        public Nullable<bool> bit_is_editable { get; set; }
        public Nullable<System.DateTime> date_pay_date { get; set; }
        public Nullable<decimal> suministro { get; set; }
        public Nullable<decimal> distribución { get; set; }
        public Nullable<decimal> tarifa_transmision { get; set; }
        public Nullable<decimal> operación_cenace { get; set; }
        public Nullable<decimal> capacidad { get; set; }
        public Nullable<decimal> cre_servicios_conexos { get; set; }
        public Nullable<decimal> precio_suministro { get; set; }
        public Nullable<decimal> precio_distribucion { get; set; }
        public Nullable<decimal> precio_transmision { get; set; }
        public Nullable<decimal> precio_cenace { get; set; }
        public Nullable<decimal> precio_energia { get; set; }
        public Nullable<decimal> precio_capacidad { get; set; }
        public Nullable<decimal> precio_cre_servicios_conexos { get; set; }
        public Nullable<decimal> precio_dos_porciento_baja_tension { get; set; }
        public Nullable<decimal> precio_decuento_bonificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice_details> tbl_invoice_details { get; set; }
        public virtual tbl_user_master tbl_user_master { get; set; }
    }
}
