//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMVCChart
    {
        public int ChartID { get; set; }
        public Nullable<int> Growth_Year { get; set; }
        public Nullable<double> Growth_Value { get; set; }
    }
}
