//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_TenantMNGEntities : DbContext
    {
        public DB_TenantMNGEntities()
            : base("name=DB_TenantMNGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UDI> UDIS { get; set; }
        public virtual DbSet<tbl_pm_billing_hours> tbl_pm_billing_hours { get; set; }
        public virtual DbSet<tbl_template> tbl_template { get; set; }
        public virtual DbSet<tbl_tenant_billing_info> tbl_tenant_billing_info { get; set; }
        public virtual DbSet<tbl_tenant_contract> tbl_tenant_contract { get; set; }
        public virtual DbSet<tbl_tenant_email_setup> tbl_tenant_email_setup { get; set; }
        public virtual DbSet<tbl_tenant_meter> tbl_tenant_meter { get; set; }
        public virtual DbSet<tbl_tenant_settings> tbl_tenant_settings { get; set; }
        public virtual DbSet<tbl_user_master> tbl_user_master { get; set; }
        public virtual DbSet<tbl_user_type> tbl_user_type { get; set; }
        public virtual DbSet<tbl_zone_master> tbl_zone_master { get; set; }
        public virtual DbSet<tblMVCChart> tblMVCCharts { get; set; }
        public virtual DbSet<tbl_invoice> tbl_invoice { get; set; }
        public virtual DbSet<tbl_invoice_details> tbl_invoice_details { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> tbl_insert_zone(string str_decription, string str_override, Nullable<bool> bit_status)
        {
            var str_decriptionParameter = str_decription != null ?
                new ObjectParameter("str_decription", str_decription) :
                new ObjectParameter("str_decription", typeof(string));
    
            var str_overrideParameter = str_override != null ?
                new ObjectParameter("str_override", str_override) :
                new ObjectParameter("str_override", typeof(string));
    
            var bit_statusParameter = bit_status.HasValue ?
                new ObjectParameter("bit_status", bit_status) :
                new ObjectParameter("bit_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("tbl_insert_zone", str_decriptionParameter, str_overrideParameter, bit_statusParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_change_password(Nullable<int> int_id, string str_new_password)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var str_new_passwordParameter = str_new_password != null ?
                new ObjectParameter("str_new_password", str_new_password) :
                new ObjectParameter("str_new_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_change_password", int_idParameter, str_new_passwordParameter);
        }
    
        public virtual int usp_change_profile(Nullable<int> int_id, string str_comp_name, string str_contact_name, string str_add_1, string str_add_2, string str_city, string str_state, Nullable<int> int_pin_code, string str_country, string str_email)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var str_comp_nameParameter = str_comp_name != null ?
                new ObjectParameter("str_comp_name", str_comp_name) :
                new ObjectParameter("str_comp_name", typeof(string));
    
            var str_contact_nameParameter = str_contact_name != null ?
                new ObjectParameter("str_contact_name", str_contact_name) :
                new ObjectParameter("str_contact_name", typeof(string));
    
            var str_add_1Parameter = str_add_1 != null ?
                new ObjectParameter("str_add_1", str_add_1) :
                new ObjectParameter("str_add_1", typeof(string));
    
            var str_add_2Parameter = str_add_2 != null ?
                new ObjectParameter("str_add_2", str_add_2) :
                new ObjectParameter("str_add_2", typeof(string));
    
            var str_cityParameter = str_city != null ?
                new ObjectParameter("str_city", str_city) :
                new ObjectParameter("str_city", typeof(string));
    
            var str_stateParameter = str_state != null ?
                new ObjectParameter("str_state", str_state) :
                new ObjectParameter("str_state", typeof(string));
    
            var int_pin_codeParameter = int_pin_code.HasValue ?
                new ObjectParameter("int_pin_code", int_pin_code) :
                new ObjectParameter("int_pin_code", typeof(int));
    
            var str_countryParameter = str_country != null ?
                new ObjectParameter("str_country", str_country) :
                new ObjectParameter("str_country", typeof(string));
    
            var str_emailParameter = str_email != null ?
                new ObjectParameter("str_email", str_email) :
                new ObjectParameter("str_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_change_profile", int_idParameter, str_comp_nameParameter, str_contact_nameParameter, str_add_1Parameter, str_add_2Parameter, str_cityParameter, str_stateParameter, int_pin_codeParameter, str_countryParameter, str_emailParameter);
        }
    
        public virtual int usp_delete_invocie(Nullable<int> int_invoice_id)
        {
            var int_invoice_idParameter = int_invoice_id.HasValue ?
                new ObjectParameter("int_invoice_id", int_invoice_id) :
                new ObjectParameter("int_invoice_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_invocie", int_invoice_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_delete_tenant_meter(Nullable<int> int_id)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_delete_tenant_meter", int_idParameter);
        }
    
        public virtual int usp_delete_user(Nullable<int> int_id)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_user", int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_detach_meter(Nullable<int> int_id)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_detach_meter", int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_detach_tenant_meter(Nullable<int> int_id, string str_meter_id)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var str_meter_idParameter = str_meter_id != null ?
                new ObjectParameter("str_meter_id", str_meter_id) :
                new ObjectParameter("str_meter_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_detach_tenant_meter", int_idParameter, str_meter_idParameter);
        }
    
        public virtual int usp_insert_invoice(ObjectParameter int_id, Nullable<int> int_tenant_id, Nullable<bool> bit_tenant_active, Nullable<System.DateTime> date_s_bill_date, Nullable<System.DateTime> date_e_bill_date, Nullable<decimal> dec_total, Nullable<decimal> dec_tax_amt, Nullable<bool> bit_is_editable, Nullable<System.DateTime> date_pay_date, Nullable<decimal> suministro, Nullable<decimal> distribución, Nullable<decimal> tarifa_transmision, Nullable<decimal> operación_cenace, Nullable<decimal> capacidad, Nullable<decimal> cre_servicios_conexos)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var bit_tenant_activeParameter = bit_tenant_active.HasValue ?
                new ObjectParameter("bit_tenant_active", bit_tenant_active) :
                new ObjectParameter("bit_tenant_active", typeof(bool));
    
            var date_s_bill_dateParameter = date_s_bill_date.HasValue ?
                new ObjectParameter("date_s_bill_date", date_s_bill_date) :
                new ObjectParameter("date_s_bill_date", typeof(System.DateTime));
    
            var date_e_bill_dateParameter = date_e_bill_date.HasValue ?
                new ObjectParameter("date_e_bill_date", date_e_bill_date) :
                new ObjectParameter("date_e_bill_date", typeof(System.DateTime));
    
            var dec_totalParameter = dec_total.HasValue ?
                new ObjectParameter("dec_total", dec_total) :
                new ObjectParameter("dec_total", typeof(decimal));
    
            var dec_tax_amtParameter = dec_tax_amt.HasValue ?
                new ObjectParameter("dec_tax_amt", dec_tax_amt) :
                new ObjectParameter("dec_tax_amt", typeof(decimal));
    
            var bit_is_editableParameter = bit_is_editable.HasValue ?
                new ObjectParameter("bit_is_editable", bit_is_editable) :
                new ObjectParameter("bit_is_editable", typeof(bool));
    
            var date_pay_dateParameter = date_pay_date.HasValue ?
                new ObjectParameter("date_pay_date", date_pay_date) :
                new ObjectParameter("date_pay_date", typeof(System.DateTime));
    
            var suministroParameter = suministro.HasValue ?
                new ObjectParameter("suministro", suministro) :
                new ObjectParameter("suministro", typeof(decimal));
    
            var distribuciónParameter = distribución.HasValue ?
                new ObjectParameter("distribución", distribución) :
                new ObjectParameter("distribución", typeof(decimal));
    
            var tarifa_transmisionParameter = tarifa_transmision.HasValue ?
                new ObjectParameter("tarifa_transmision", tarifa_transmision) :
                new ObjectParameter("tarifa_transmision", typeof(decimal));
    
            var operación_cenaceParameter = operación_cenace.HasValue ?
                new ObjectParameter("operación_cenace", operación_cenace) :
                new ObjectParameter("operación_cenace", typeof(decimal));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("capacidad", capacidad) :
                new ObjectParameter("capacidad", typeof(decimal));
    
            var cre_servicios_conexosParameter = cre_servicios_conexos.HasValue ?
                new ObjectParameter("cre_servicios_conexos", cre_servicios_conexos) :
                new ObjectParameter("cre_servicios_conexos", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_invoice", int_id, int_tenant_idParameter, bit_tenant_activeParameter, date_s_bill_dateParameter, date_e_bill_dateParameter, dec_totalParameter, dec_tax_amtParameter, bit_is_editableParameter, date_pay_dateParameter, suministroParameter, distribuciónParameter, tarifa_transmisionParameter, operación_cenaceParameter, capacidadParameter, cre_servicios_conexosParameter);
        }
    
        public virtual int usp_insert_invoice_details(string str_meter_id, Nullable<int> int_invoice_id, Nullable<decimal> dec_peak_energy, Nullable<decimal> dec_peak_energy_rate, Nullable<decimal> dec_peak_energy_amt, Nullable<decimal> dec_inter_energy, Nullable<decimal> dec_inter_energy_rate, Nullable<decimal> dec_inter_energy_amt, Nullable<decimal> dec_base_energy, Nullable<decimal> dec_base_rate, Nullable<decimal> dec_base_amt, Nullable<decimal> demanda_base, Nullable<decimal> demanda_intermedia, Nullable<decimal> demanda_punta, Nullable<decimal> energia_activa, Nullable<decimal> energia_reactiva)
        {
            var str_meter_idParameter = str_meter_id != null ?
                new ObjectParameter("str_meter_id", str_meter_id) :
                new ObjectParameter("str_meter_id", typeof(string));
    
            var int_invoice_idParameter = int_invoice_id.HasValue ?
                new ObjectParameter("int_invoice_id", int_invoice_id) :
                new ObjectParameter("int_invoice_id", typeof(int));
    
            var dec_peak_energyParameter = dec_peak_energy.HasValue ?
                new ObjectParameter("dec_peak_energy", dec_peak_energy) :
                new ObjectParameter("dec_peak_energy", typeof(decimal));
    
            var dec_peak_energy_rateParameter = dec_peak_energy_rate.HasValue ?
                new ObjectParameter("dec_peak_energy_rate", dec_peak_energy_rate) :
                new ObjectParameter("dec_peak_energy_rate", typeof(decimal));
    
            var dec_peak_energy_amtParameter = dec_peak_energy_amt.HasValue ?
                new ObjectParameter("dec_peak_energy_amt", dec_peak_energy_amt) :
                new ObjectParameter("dec_peak_energy_amt", typeof(decimal));
    
            var dec_inter_energyParameter = dec_inter_energy.HasValue ?
                new ObjectParameter("dec_inter_energy", dec_inter_energy) :
                new ObjectParameter("dec_inter_energy", typeof(decimal));
    
            var dec_inter_energy_rateParameter = dec_inter_energy_rate.HasValue ?
                new ObjectParameter("dec_inter_energy_rate", dec_inter_energy_rate) :
                new ObjectParameter("dec_inter_energy_rate", typeof(decimal));
    
            var dec_inter_energy_amtParameter = dec_inter_energy_amt.HasValue ?
                new ObjectParameter("dec_inter_energy_amt", dec_inter_energy_amt) :
                new ObjectParameter("dec_inter_energy_amt", typeof(decimal));
    
            var dec_base_energyParameter = dec_base_energy.HasValue ?
                new ObjectParameter("dec_base_energy", dec_base_energy) :
                new ObjectParameter("dec_base_energy", typeof(decimal));
    
            var dec_base_rateParameter = dec_base_rate.HasValue ?
                new ObjectParameter("dec_base_rate", dec_base_rate) :
                new ObjectParameter("dec_base_rate", typeof(decimal));
    
            var dec_base_amtParameter = dec_base_amt.HasValue ?
                new ObjectParameter("dec_base_amt", dec_base_amt) :
                new ObjectParameter("dec_base_amt", typeof(decimal));
    
            var demanda_baseParameter = demanda_base.HasValue ?
                new ObjectParameter("demanda_base", demanda_base) :
                new ObjectParameter("demanda_base", typeof(decimal));
    
            var demanda_intermediaParameter = demanda_intermedia.HasValue ?
                new ObjectParameter("demanda_intermedia", demanda_intermedia) :
                new ObjectParameter("demanda_intermedia", typeof(decimal));
    
            var demanda_puntaParameter = demanda_punta.HasValue ?
                new ObjectParameter("demanda_punta", demanda_punta) :
                new ObjectParameter("demanda_punta", typeof(decimal));
    
            var energia_activaParameter = energia_activa.HasValue ?
                new ObjectParameter("energia_activa", energia_activa) :
                new ObjectParameter("energia_activa", typeof(decimal));
    
            var energia_reactivaParameter = energia_reactiva.HasValue ?
                new ObjectParameter("energia_reactiva", energia_reactiva) :
                new ObjectParameter("energia_reactiva", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_invoice_details", str_meter_idParameter, int_invoice_idParameter, dec_peak_energyParameter, dec_peak_energy_rateParameter, dec_peak_energy_amtParameter, dec_inter_energyParameter, dec_inter_energy_rateParameter, dec_inter_energy_amtParameter, dec_base_energyParameter, dec_base_rateParameter, dec_base_amtParameter, demanda_baseParameter, demanda_intermediaParameter, demanda_puntaParameter, energia_activaParameter, energia_reactivaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_insert_pm_billing_hours(Nullable<int> int_pm_id, string str_peak_s_time_m, string str_peak_e_time_m, string str_inter_s_time_1_m, string str_inter_e_time_1_m, string str_inter_s_time_2_m, string str_inter_e_time_2_m, string str_base_s_time_m, string str_base_e_time_m, string str_base_s_time_sat, string str_base_e_time_sat, string str_inter_s_time_sat, string str_inter_e_time_sat, string str_inter_s_time_2_sa, string str_inter_e_time_2_sa, string str_peak_s_time_sat, string str_peak_e_time_sat, string str_base_s_time_sun, string str_base_e_time_sun, string str_inter_s_time_sun, string str_inter_e_time_sun)
        {
            var int_pm_idParameter = int_pm_id.HasValue ?
                new ObjectParameter("int_pm_id", int_pm_id) :
                new ObjectParameter("int_pm_id", typeof(int));
    
            var str_peak_s_time_mParameter = str_peak_s_time_m != null ?
                new ObjectParameter("str_peak_s_time_m", str_peak_s_time_m) :
                new ObjectParameter("str_peak_s_time_m", typeof(string));
    
            var str_peak_e_time_mParameter = str_peak_e_time_m != null ?
                new ObjectParameter("str_peak_e_time_m", str_peak_e_time_m) :
                new ObjectParameter("str_peak_e_time_m", typeof(string));
    
            var str_inter_s_time_1_mParameter = str_inter_s_time_1_m != null ?
                new ObjectParameter("str_inter_s_time_1_m", str_inter_s_time_1_m) :
                new ObjectParameter("str_inter_s_time_1_m", typeof(string));
    
            var str_inter_e_time_1_mParameter = str_inter_e_time_1_m != null ?
                new ObjectParameter("str_inter_e_time_1_m", str_inter_e_time_1_m) :
                new ObjectParameter("str_inter_e_time_1_m", typeof(string));
    
            var str_inter_s_time_2_mParameter = str_inter_s_time_2_m != null ?
                new ObjectParameter("str_inter_s_time_2_m", str_inter_s_time_2_m) :
                new ObjectParameter("str_inter_s_time_2_m", typeof(string));
    
            var str_inter_e_time_2_mParameter = str_inter_e_time_2_m != null ?
                new ObjectParameter("str_inter_e_time_2_m", str_inter_e_time_2_m) :
                new ObjectParameter("str_inter_e_time_2_m", typeof(string));
    
            var str_base_s_time_mParameter = str_base_s_time_m != null ?
                new ObjectParameter("str_base_s_time_m", str_base_s_time_m) :
                new ObjectParameter("str_base_s_time_m", typeof(string));
    
            var str_base_e_time_mParameter = str_base_e_time_m != null ?
                new ObjectParameter("str_base_e_time_m", str_base_e_time_m) :
                new ObjectParameter("str_base_e_time_m", typeof(string));
    
            var str_base_s_time_satParameter = str_base_s_time_sat != null ?
                new ObjectParameter("str_base_s_time_sat", str_base_s_time_sat) :
                new ObjectParameter("str_base_s_time_sat", typeof(string));
    
            var str_base_e_time_satParameter = str_base_e_time_sat != null ?
                new ObjectParameter("str_base_e_time_sat", str_base_e_time_sat) :
                new ObjectParameter("str_base_e_time_sat", typeof(string));
    
            var str_inter_s_time_satParameter = str_inter_s_time_sat != null ?
                new ObjectParameter("str_inter_s_time_sat", str_inter_s_time_sat) :
                new ObjectParameter("str_inter_s_time_sat", typeof(string));
    
            var str_inter_e_time_satParameter = str_inter_e_time_sat != null ?
                new ObjectParameter("str_inter_e_time_sat", str_inter_e_time_sat) :
                new ObjectParameter("str_inter_e_time_sat", typeof(string));
    
            var str_inter_s_time_2_saParameter = str_inter_s_time_2_sa != null ?
                new ObjectParameter("str_inter_s_time_2_sa", str_inter_s_time_2_sa) :
                new ObjectParameter("str_inter_s_time_2_sa", typeof(string));
    
            var str_inter_e_time_2_saParameter = str_inter_e_time_2_sa != null ?
                new ObjectParameter("str_inter_e_time_2_sa", str_inter_e_time_2_sa) :
                new ObjectParameter("str_inter_e_time_2_sa", typeof(string));
    
            var str_peak_s_time_satParameter = str_peak_s_time_sat != null ?
                new ObjectParameter("str_peak_s_time_sat", str_peak_s_time_sat) :
                new ObjectParameter("str_peak_s_time_sat", typeof(string));
    
            var str_peak_e_time_satParameter = str_peak_e_time_sat != null ?
                new ObjectParameter("str_peak_e_time_sat", str_peak_e_time_sat) :
                new ObjectParameter("str_peak_e_time_sat", typeof(string));
    
            var str_base_s_time_sunParameter = str_base_s_time_sun != null ?
                new ObjectParameter("str_base_s_time_sun", str_base_s_time_sun) :
                new ObjectParameter("str_base_s_time_sun", typeof(string));
    
            var str_base_e_time_sunParameter = str_base_e_time_sun != null ?
                new ObjectParameter("str_base_e_time_sun", str_base_e_time_sun) :
                new ObjectParameter("str_base_e_time_sun", typeof(string));
    
            var str_inter_s_time_sunParameter = str_inter_s_time_sun != null ?
                new ObjectParameter("str_inter_s_time_sun", str_inter_s_time_sun) :
                new ObjectParameter("str_inter_s_time_sun", typeof(string));
    
            var str_inter_e_time_sunParameter = str_inter_e_time_sun != null ?
                new ObjectParameter("str_inter_e_time_sun", str_inter_e_time_sun) :
                new ObjectParameter("str_inter_e_time_sun", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_insert_pm_billing_hours", int_pm_idParameter, str_peak_s_time_mParameter, str_peak_e_time_mParameter, str_inter_s_time_1_mParameter, str_inter_e_time_1_mParameter, str_inter_s_time_2_mParameter, str_inter_e_time_2_mParameter, str_base_s_time_mParameter, str_base_e_time_mParameter, str_base_s_time_satParameter, str_base_e_time_satParameter, str_inter_s_time_satParameter, str_inter_e_time_satParameter, str_inter_s_time_2_saParameter, str_inter_e_time_2_saParameter, str_peak_s_time_satParameter, str_peak_e_time_satParameter, str_base_s_time_sunParameter, str_base_e_time_sunParameter, str_inter_s_time_sunParameter, str_inter_e_time_sunParameter);
        }
    
        public virtual int usp_insert_tbl_tenant_email(Nullable<int> int_tenant_id, string str_from_email, string str_cc_email, string str_bcc_email, string str_subject, string str_body)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var str_from_emailParameter = str_from_email != null ?
                new ObjectParameter("str_from_email", str_from_email) :
                new ObjectParameter("str_from_email", typeof(string));
    
            var str_cc_emailParameter = str_cc_email != null ?
                new ObjectParameter("str_cc_email", str_cc_email) :
                new ObjectParameter("str_cc_email", typeof(string));
    
            var str_bcc_emailParameter = str_bcc_email != null ?
                new ObjectParameter("str_bcc_email", str_bcc_email) :
                new ObjectParameter("str_bcc_email", typeof(string));
    
            var str_subjectParameter = str_subject != null ?
                new ObjectParameter("str_subject", str_subject) :
                new ObjectParameter("str_subject", typeof(string));
    
            var str_bodyParameter = str_body != null ?
                new ObjectParameter("str_body", str_body) :
                new ObjectParameter("str_body", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_tbl_tenant_email", int_tenant_idParameter, str_from_emailParameter, str_cc_emailParameter, str_bcc_emailParameter, str_subjectParameter, str_bodyParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_insert_tenant_billing_info(Nullable<int> int_tenant_id, Nullable<int> int_template_id, Nullable<decimal> dec_rate, Nullable<bool> bit_is_seasonal_rate, Nullable<decimal> dec_seasonal_multi_rate, Nullable<bool> bit_is_surchare, Nullable<decimal> dec_surcharge_amt, string str_min_billable_over, string str_charge_tenant_min, string str_charge_tenant_max, Nullable<bool> bit_is_consolidate_zone, Nullable<bool> bit_is_print, Nullable<bool> bit_is_file, Nullable<int> int_type, string str_email)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var int_template_idParameter = int_template_id.HasValue ?
                new ObjectParameter("int_template_id", int_template_id) :
                new ObjectParameter("int_template_id", typeof(int));
    
            var dec_rateParameter = dec_rate.HasValue ?
                new ObjectParameter("dec_rate", dec_rate) :
                new ObjectParameter("dec_rate", typeof(decimal));
    
            var bit_is_seasonal_rateParameter = bit_is_seasonal_rate.HasValue ?
                new ObjectParameter("bit_is_seasonal_rate", bit_is_seasonal_rate) :
                new ObjectParameter("bit_is_seasonal_rate", typeof(bool));
    
            var dec_seasonal_multi_rateParameter = dec_seasonal_multi_rate.HasValue ?
                new ObjectParameter("dec_seasonal_multi_rate", dec_seasonal_multi_rate) :
                new ObjectParameter("dec_seasonal_multi_rate", typeof(decimal));
    
            var bit_is_surchareParameter = bit_is_surchare.HasValue ?
                new ObjectParameter("bit_is_surchare", bit_is_surchare) :
                new ObjectParameter("bit_is_surchare", typeof(bool));
    
            var dec_surcharge_amtParameter = dec_surcharge_amt.HasValue ?
                new ObjectParameter("dec_surcharge_amt", dec_surcharge_amt) :
                new ObjectParameter("dec_surcharge_amt", typeof(decimal));
    
            var str_min_billable_overParameter = str_min_billable_over != null ?
                new ObjectParameter("str_min_billable_over", str_min_billable_over) :
                new ObjectParameter("str_min_billable_over", typeof(string));
    
            var str_charge_tenant_minParameter = str_charge_tenant_min != null ?
                new ObjectParameter("str_charge_tenant_min", str_charge_tenant_min) :
                new ObjectParameter("str_charge_tenant_min", typeof(string));
    
            var str_charge_tenant_maxParameter = str_charge_tenant_max != null ?
                new ObjectParameter("str_charge_tenant_max", str_charge_tenant_max) :
                new ObjectParameter("str_charge_tenant_max", typeof(string));
    
            var bit_is_consolidate_zoneParameter = bit_is_consolidate_zone.HasValue ?
                new ObjectParameter("bit_is_consolidate_zone", bit_is_consolidate_zone) :
                new ObjectParameter("bit_is_consolidate_zone", typeof(bool));
    
            var bit_is_printParameter = bit_is_print.HasValue ?
                new ObjectParameter("bit_is_print", bit_is_print) :
                new ObjectParameter("bit_is_print", typeof(bool));
    
            var bit_is_fileParameter = bit_is_file.HasValue ?
                new ObjectParameter("bit_is_file", bit_is_file) :
                new ObjectParameter("bit_is_file", typeof(bool));
    
            var int_typeParameter = int_type.HasValue ?
                new ObjectParameter("int_type", int_type) :
                new ObjectParameter("int_type", typeof(int));
    
            var str_emailParameter = str_email != null ?
                new ObjectParameter("str_email", str_email) :
                new ObjectParameter("str_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_insert_tenant_billing_info", int_tenant_idParameter, int_template_idParameter, dec_rateParameter, bit_is_seasonal_rateParameter, dec_seasonal_multi_rateParameter, bit_is_surchareParameter, dec_surcharge_amtParameter, str_min_billable_overParameter, str_charge_tenant_minParameter, str_charge_tenant_maxParameter, bit_is_consolidate_zoneParameter, bit_is_printParameter, bit_is_fileParameter, int_typeParameter, str_emailParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_insert_tenant_contract(Nullable<int> int_tenant_id, Nullable<System.DateTime> s_date, Nullable<System.DateTime> e_date)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var s_dateParameter = s_date.HasValue ?
                new ObjectParameter("s_date", s_date) :
                new ObjectParameter("s_date", typeof(System.DateTime));
    
            var e_dateParameter = e_date.HasValue ?
                new ObjectParameter("e_date", e_date) :
                new ObjectParameter("e_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_insert_tenant_contract", int_tenant_idParameter, s_dateParameter, e_dateParameter);
        }
    
        public virtual int usp_insert_tenant_meter(Nullable<int> int_tenant_id, string str_meter_id, ObjectParameter int_id)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var str_meter_idParameter = str_meter_id != null ?
                new ObjectParameter("str_meter_id", str_meter_id) :
                new ObjectParameter("str_meter_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_tenant_meter", int_tenant_idParameter, str_meter_idParameter, int_id);
        }
    
        public virtual int usp_insert_tenant_setting(Nullable<int> int_tenant_id, Nullable<decimal> dec_demanda_facturable, Nullable<decimal> dec_total_ene)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var dec_demanda_facturableParameter = dec_demanda_facturable.HasValue ?
                new ObjectParameter("dec_demanda_facturable", dec_demanda_facturable) :
                new ObjectParameter("dec_demanda_facturable", typeof(decimal));
    
            var dec_total_eneParameter = dec_total_ene.HasValue ?
                new ObjectParameter("dec_total_ene", dec_total_ene) :
                new ObjectParameter("dec_total_ene", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_tenant_setting", int_tenant_idParameter, dec_demanda_facturableParameter, dec_total_eneParameter);
        }
    
        public virtual int usp_insert_user(string str_comp_name, string str_contact_name, string str_add_1, string str_add_2, string str_city, string str_state, Nullable<int> int_pin_code, string str_country, string str_email, Nullable<int> int_user_type_id, string str_user_name, string str_password, Nullable<int> int_pm_id, ObjectParameter int_user_id, Nullable<int> int_invoice_period)
        {
            var str_comp_nameParameter = str_comp_name != null ?
                new ObjectParameter("str_comp_name", str_comp_name) :
                new ObjectParameter("str_comp_name", typeof(string));
    
            var str_contact_nameParameter = str_contact_name != null ?
                new ObjectParameter("str_contact_name", str_contact_name) :
                new ObjectParameter("str_contact_name", typeof(string));
    
            var str_add_1Parameter = str_add_1 != null ?
                new ObjectParameter("str_add_1", str_add_1) :
                new ObjectParameter("str_add_1", typeof(string));
    
            var str_add_2Parameter = str_add_2 != null ?
                new ObjectParameter("str_add_2", str_add_2) :
                new ObjectParameter("str_add_2", typeof(string));
    
            var str_cityParameter = str_city != null ?
                new ObjectParameter("str_city", str_city) :
                new ObjectParameter("str_city", typeof(string));
    
            var str_stateParameter = str_state != null ?
                new ObjectParameter("str_state", str_state) :
                new ObjectParameter("str_state", typeof(string));
    
            var int_pin_codeParameter = int_pin_code.HasValue ?
                new ObjectParameter("int_pin_code", int_pin_code) :
                new ObjectParameter("int_pin_code", typeof(int));
    
            var str_countryParameter = str_country != null ?
                new ObjectParameter("str_country", str_country) :
                new ObjectParameter("str_country", typeof(string));
    
            var str_emailParameter = str_email != null ?
                new ObjectParameter("str_email", str_email) :
                new ObjectParameter("str_email", typeof(string));
    
            var int_user_type_idParameter = int_user_type_id.HasValue ?
                new ObjectParameter("int_user_type_id", int_user_type_id) :
                new ObjectParameter("int_user_type_id", typeof(int));
    
            var str_user_nameParameter = str_user_name != null ?
                new ObjectParameter("str_user_name", str_user_name) :
                new ObjectParameter("str_user_name", typeof(string));
    
            var str_passwordParameter = str_password != null ?
                new ObjectParameter("str_password", str_password) :
                new ObjectParameter("str_password", typeof(string));
    
            var int_pm_idParameter = int_pm_id.HasValue ?
                new ObjectParameter("int_pm_id", int_pm_id) :
                new ObjectParameter("int_pm_id", typeof(int));
    
            var int_invoice_periodParameter = int_invoice_period.HasValue ?
                new ObjectParameter("int_invoice_period", int_invoice_period) :
                new ObjectParameter("int_invoice_period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_user", str_comp_nameParameter, str_contact_nameParameter, str_add_1Parameter, str_add_2Parameter, str_cityParameter, str_stateParameter, int_pin_codeParameter, str_countryParameter, str_emailParameter, int_user_type_idParameter, str_user_nameParameter, str_passwordParameter, int_pm_idParameter, int_user_id, int_invoice_periodParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_test(Nullable<System.DateTime> sdate, Nullable<System.DateTime> edate, Nullable<int> int_tenant_id)
        {
            var sdateParameter = sdate.HasValue ?
                new ObjectParameter("sdate", sdate) :
                new ObjectParameter("sdate", typeof(System.DateTime));
    
            var edateParameter = edate.HasValue ?
                new ObjectParameter("edate", edate) :
                new ObjectParameter("edate", typeof(System.DateTime));
    
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_test", sdateParameter, edateParameter, int_tenant_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_update_bill_rate(Nullable<int> int_id, Nullable<decimal> dec_rate, Nullable<decimal> dec_seasonal_rate, Nullable<decimal> dec_surcharge_amt)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var dec_rateParameter = dec_rate.HasValue ?
                new ObjectParameter("dec_rate", dec_rate) :
                new ObjectParameter("dec_rate", typeof(decimal));
    
            var dec_seasonal_rateParameter = dec_seasonal_rate.HasValue ?
                new ObjectParameter("dec_seasonal_rate", dec_seasonal_rate) :
                new ObjectParameter("dec_seasonal_rate", typeof(decimal));
    
            var dec_surcharge_amtParameter = dec_surcharge_amt.HasValue ?
                new ObjectParameter("dec_surcharge_amt", dec_surcharge_amt) :
                new ObjectParameter("dec_surcharge_amt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_update_bill_rate", int_idParameter, dec_rateParameter, dec_seasonal_rateParameter, dec_surcharge_amtParameter);
        }
    
        public virtual int usp_update_invoice(Nullable<int> int_id, Nullable<bool> bit_tenant_active, Nullable<System.DateTime> date_s_bill_date, Nullable<System.DateTime> date_e_bill_date, Nullable<decimal> dec_total, Nullable<decimal> dec_tax_amt, Nullable<System.DateTime> date_pay_date, Nullable<decimal> suministro, Nullable<decimal> distribución, Nullable<decimal> tarifa_transmision, Nullable<decimal> operación_cenace, Nullable<decimal> capacidad, Nullable<decimal> cre_servicios_conexos, Nullable<int> int_tenant_id)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var bit_tenant_activeParameter = bit_tenant_active.HasValue ?
                new ObjectParameter("bit_tenant_active", bit_tenant_active) :
                new ObjectParameter("bit_tenant_active", typeof(bool));
    
            var date_s_bill_dateParameter = date_s_bill_date.HasValue ?
                new ObjectParameter("date_s_bill_date", date_s_bill_date) :
                new ObjectParameter("date_s_bill_date", typeof(System.DateTime));
    
            var date_e_bill_dateParameter = date_e_bill_date.HasValue ?
                new ObjectParameter("date_e_bill_date", date_e_bill_date) :
                new ObjectParameter("date_e_bill_date", typeof(System.DateTime));
    
            var dec_totalParameter = dec_total.HasValue ?
                new ObjectParameter("dec_total", dec_total) :
                new ObjectParameter("dec_total", typeof(decimal));
    
            var dec_tax_amtParameter = dec_tax_amt.HasValue ?
                new ObjectParameter("dec_tax_amt", dec_tax_amt) :
                new ObjectParameter("dec_tax_amt", typeof(decimal));
    
            var date_pay_dateParameter = date_pay_date.HasValue ?
                new ObjectParameter("date_pay_date", date_pay_date) :
                new ObjectParameter("date_pay_date", typeof(System.DateTime));
    
            var suministroParameter = suministro.HasValue ?
                new ObjectParameter("suministro", suministro) :
                new ObjectParameter("suministro", typeof(decimal));
    
            var distribuciónParameter = distribución.HasValue ?
                new ObjectParameter("distribución", distribución) :
                new ObjectParameter("distribución", typeof(decimal));
    
            var tarifa_transmisionParameter = tarifa_transmision.HasValue ?
                new ObjectParameter("tarifa_transmision", tarifa_transmision) :
                new ObjectParameter("tarifa_transmision", typeof(decimal));
    
            var operación_cenaceParameter = operación_cenace.HasValue ?
                new ObjectParameter("operación_cenace", operación_cenace) :
                new ObjectParameter("operación_cenace", typeof(decimal));
    
            var capacidadParameter = capacidad.HasValue ?
                new ObjectParameter("capacidad", capacidad) :
                new ObjectParameter("capacidad", typeof(decimal));
    
            var cre_servicios_conexosParameter = cre_servicios_conexos.HasValue ?
                new ObjectParameter("cre_servicios_conexos", cre_servicios_conexos) :
                new ObjectParameter("cre_servicios_conexos", typeof(decimal));
    
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_invoice", int_idParameter, bit_tenant_activeParameter, date_s_bill_dateParameter, date_e_bill_dateParameter, dec_totalParameter, dec_tax_amtParameter, date_pay_dateParameter, suministroParameter, distribuciónParameter, tarifa_transmisionParameter, operación_cenaceParameter, capacidadParameter, cre_servicios_conexosParameter, int_tenant_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_update_pm_billing_hours(Nullable<int> int_pm_id, string str_peak_s_time_m, string str_peak_e_time_m, string str_inter_s_time_1_m, string str_inter_e_time_1_m, string str_inter_s_time_2_m, string str_inter_e_time_2_m, string str_base_s_time_m, string str_base_e_time_m, string str_base_s_time_sat, string str_base_e_time_sat, string str_inter_s_time_sat, string str_inter_e_time_sat, string str_inter_s_time_2_sat, string str_inter_e_time_2_sat, string str_peak_s_time_sat, string str_peak_e_time_sat, string str_base_s_time_sun, string str_base_e_time_sun, string str_inter_s_time_sun, string str_inter_e_time_sun)
        {
            var int_pm_idParameter = int_pm_id.HasValue ?
                new ObjectParameter("int_pm_id", int_pm_id) :
                new ObjectParameter("int_pm_id", typeof(int));
    
            var str_peak_s_time_mParameter = str_peak_s_time_m != null ?
                new ObjectParameter("str_peak_s_time_m", str_peak_s_time_m) :
                new ObjectParameter("str_peak_s_time_m", typeof(string));
    
            var str_peak_e_time_mParameter = str_peak_e_time_m != null ?
                new ObjectParameter("str_peak_e_time_m", str_peak_e_time_m) :
                new ObjectParameter("str_peak_e_time_m", typeof(string));
    
            var str_inter_s_time_1_mParameter = str_inter_s_time_1_m != null ?
                new ObjectParameter("str_inter_s_time_1_m", str_inter_s_time_1_m) :
                new ObjectParameter("str_inter_s_time_1_m", typeof(string));
    
            var str_inter_e_time_1_mParameter = str_inter_e_time_1_m != null ?
                new ObjectParameter("str_inter_e_time_1_m", str_inter_e_time_1_m) :
                new ObjectParameter("str_inter_e_time_1_m", typeof(string));
    
            var str_inter_s_time_2_mParameter = str_inter_s_time_2_m != null ?
                new ObjectParameter("str_inter_s_time_2_m", str_inter_s_time_2_m) :
                new ObjectParameter("str_inter_s_time_2_m", typeof(string));
    
            var str_inter_e_time_2_mParameter = str_inter_e_time_2_m != null ?
                new ObjectParameter("str_inter_e_time_2_m", str_inter_e_time_2_m) :
                new ObjectParameter("str_inter_e_time_2_m", typeof(string));
    
            var str_base_s_time_mParameter = str_base_s_time_m != null ?
                new ObjectParameter("str_base_s_time_m", str_base_s_time_m) :
                new ObjectParameter("str_base_s_time_m", typeof(string));
    
            var str_base_e_time_mParameter = str_base_e_time_m != null ?
                new ObjectParameter("str_base_e_time_m", str_base_e_time_m) :
                new ObjectParameter("str_base_e_time_m", typeof(string));
    
            var str_base_s_time_satParameter = str_base_s_time_sat != null ?
                new ObjectParameter("str_base_s_time_sat", str_base_s_time_sat) :
                new ObjectParameter("str_base_s_time_sat", typeof(string));
    
            var str_base_e_time_satParameter = str_base_e_time_sat != null ?
                new ObjectParameter("str_base_e_time_sat", str_base_e_time_sat) :
                new ObjectParameter("str_base_e_time_sat", typeof(string));
    
            var str_inter_s_time_satParameter = str_inter_s_time_sat != null ?
                new ObjectParameter("str_inter_s_time_sat", str_inter_s_time_sat) :
                new ObjectParameter("str_inter_s_time_sat", typeof(string));
    
            var str_inter_e_time_satParameter = str_inter_e_time_sat != null ?
                new ObjectParameter("str_inter_e_time_sat", str_inter_e_time_sat) :
                new ObjectParameter("str_inter_e_time_sat", typeof(string));
    
            var str_inter_s_time_2_satParameter = str_inter_s_time_2_sat != null ?
                new ObjectParameter("str_inter_s_time_2_sat", str_inter_s_time_2_sat) :
                new ObjectParameter("str_inter_s_time_2_sat", typeof(string));
    
            var str_inter_e_time_2_satParameter = str_inter_e_time_2_sat != null ?
                new ObjectParameter("str_inter_e_time_2_sat", str_inter_e_time_2_sat) :
                new ObjectParameter("str_inter_e_time_2_sat", typeof(string));
    
            var str_peak_s_time_satParameter = str_peak_s_time_sat != null ?
                new ObjectParameter("str_peak_s_time_sat", str_peak_s_time_sat) :
                new ObjectParameter("str_peak_s_time_sat", typeof(string));
    
            var str_peak_e_time_satParameter = str_peak_e_time_sat != null ?
                new ObjectParameter("str_peak_e_time_sat", str_peak_e_time_sat) :
                new ObjectParameter("str_peak_e_time_sat", typeof(string));
    
            var str_base_s_time_sunParameter = str_base_s_time_sun != null ?
                new ObjectParameter("str_base_s_time_sun", str_base_s_time_sun) :
                new ObjectParameter("str_base_s_time_sun", typeof(string));
    
            var str_base_e_time_sunParameter = str_base_e_time_sun != null ?
                new ObjectParameter("str_base_e_time_sun", str_base_e_time_sun) :
                new ObjectParameter("str_base_e_time_sun", typeof(string));
    
            var str_inter_s_time_sunParameter = str_inter_s_time_sun != null ?
                new ObjectParameter("str_inter_s_time_sun", str_inter_s_time_sun) :
                new ObjectParameter("str_inter_s_time_sun", typeof(string));
    
            var str_inter_e_time_sunParameter = str_inter_e_time_sun != null ?
                new ObjectParameter("str_inter_e_time_sun", str_inter_e_time_sun) :
                new ObjectParameter("str_inter_e_time_sun", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_update_pm_billing_hours", int_pm_idParameter, str_peak_s_time_mParameter, str_peak_e_time_mParameter, str_inter_s_time_1_mParameter, str_inter_e_time_1_mParameter, str_inter_s_time_2_mParameter, str_inter_e_time_2_mParameter, str_base_s_time_mParameter, str_base_e_time_mParameter, str_base_s_time_satParameter, str_base_e_time_satParameter, str_inter_s_time_satParameter, str_inter_e_time_satParameter, str_inter_s_time_2_satParameter, str_inter_e_time_2_satParameter, str_peak_s_time_satParameter, str_peak_e_time_satParameter, str_base_s_time_sunParameter, str_base_e_time_sunParameter, str_inter_s_time_sunParameter, str_inter_e_time_sunParameter);
        }
    
        public virtual int usp_update_tbl_tenant_email(Nullable<int> int_tenant_id, string str_from_email, string str_cc_email, string str_bcc_email, string str_subject, string str_body, Nullable<int> int_email_id)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var str_from_emailParameter = str_from_email != null ?
                new ObjectParameter("str_from_email", str_from_email) :
                new ObjectParameter("str_from_email", typeof(string));
    
            var str_cc_emailParameter = str_cc_email != null ?
                new ObjectParameter("str_cc_email", str_cc_email) :
                new ObjectParameter("str_cc_email", typeof(string));
    
            var str_bcc_emailParameter = str_bcc_email != null ?
                new ObjectParameter("str_bcc_email", str_bcc_email) :
                new ObjectParameter("str_bcc_email", typeof(string));
    
            var str_subjectParameter = str_subject != null ?
                new ObjectParameter("str_subject", str_subject) :
                new ObjectParameter("str_subject", typeof(string));
    
            var str_bodyParameter = str_body != null ?
                new ObjectParameter("str_body", str_body) :
                new ObjectParameter("str_body", typeof(string));
    
            var int_email_idParameter = int_email_id.HasValue ?
                new ObjectParameter("int_email_id", int_email_id) :
                new ObjectParameter("int_email_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_tbl_tenant_email", int_tenant_idParameter, str_from_emailParameter, str_cc_emailParameter, str_bcc_emailParameter, str_subjectParameter, str_bodyParameter, int_email_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_update_tenant_billing_info(Nullable<int> int_tenant_id, Nullable<int> int_template_id, Nullable<decimal> dec_rate, Nullable<bool> bit_is_seasonal_rate, Nullable<decimal> dec_seasonal_multi_rate, Nullable<bool> bit_is_surchare, Nullable<decimal> dec_surcharge_amt, string str_min_billable_over, string str_charge_tenant_min, string str_charge_tenant_max, Nullable<bool> bit_is_consolidate_zone, Nullable<bool> bit_is_print, Nullable<bool> bit_is_file, Nullable<int> int_type, string str_email, Nullable<int> int_id)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var int_template_idParameter = int_template_id.HasValue ?
                new ObjectParameter("int_template_id", int_template_id) :
                new ObjectParameter("int_template_id", typeof(int));
    
            var dec_rateParameter = dec_rate.HasValue ?
                new ObjectParameter("dec_rate", dec_rate) :
                new ObjectParameter("dec_rate", typeof(decimal));
    
            var bit_is_seasonal_rateParameter = bit_is_seasonal_rate.HasValue ?
                new ObjectParameter("bit_is_seasonal_rate", bit_is_seasonal_rate) :
                new ObjectParameter("bit_is_seasonal_rate", typeof(bool));
    
            var dec_seasonal_multi_rateParameter = dec_seasonal_multi_rate.HasValue ?
                new ObjectParameter("dec_seasonal_multi_rate", dec_seasonal_multi_rate) :
                new ObjectParameter("dec_seasonal_multi_rate", typeof(decimal));
    
            var bit_is_surchareParameter = bit_is_surchare.HasValue ?
                new ObjectParameter("bit_is_surchare", bit_is_surchare) :
                new ObjectParameter("bit_is_surchare", typeof(bool));
    
            var dec_surcharge_amtParameter = dec_surcharge_amt.HasValue ?
                new ObjectParameter("dec_surcharge_amt", dec_surcharge_amt) :
                new ObjectParameter("dec_surcharge_amt", typeof(decimal));
    
            var str_min_billable_overParameter = str_min_billable_over != null ?
                new ObjectParameter("str_min_billable_over", str_min_billable_over) :
                new ObjectParameter("str_min_billable_over", typeof(string));
    
            var str_charge_tenant_minParameter = str_charge_tenant_min != null ?
                new ObjectParameter("str_charge_tenant_min", str_charge_tenant_min) :
                new ObjectParameter("str_charge_tenant_min", typeof(string));
    
            var str_charge_tenant_maxParameter = str_charge_tenant_max != null ?
                new ObjectParameter("str_charge_tenant_max", str_charge_tenant_max) :
                new ObjectParameter("str_charge_tenant_max", typeof(string));
    
            var bit_is_consolidate_zoneParameter = bit_is_consolidate_zone.HasValue ?
                new ObjectParameter("bit_is_consolidate_zone", bit_is_consolidate_zone) :
                new ObjectParameter("bit_is_consolidate_zone", typeof(bool));
    
            var bit_is_printParameter = bit_is_print.HasValue ?
                new ObjectParameter("bit_is_print", bit_is_print) :
                new ObjectParameter("bit_is_print", typeof(bool));
    
            var bit_is_fileParameter = bit_is_file.HasValue ?
                new ObjectParameter("bit_is_file", bit_is_file) :
                new ObjectParameter("bit_is_file", typeof(bool));
    
            var int_typeParameter = int_type.HasValue ?
                new ObjectParameter("int_type", int_type) :
                new ObjectParameter("int_type", typeof(int));
    
            var str_emailParameter = str_email != null ?
                new ObjectParameter("str_email", str_email) :
                new ObjectParameter("str_email", typeof(string));
    
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_update_tenant_billing_info", int_tenant_idParameter, int_template_idParameter, dec_rateParameter, bit_is_seasonal_rateParameter, dec_seasonal_multi_rateParameter, bit_is_surchareParameter, dec_surcharge_amtParameter, str_min_billable_overParameter, str_charge_tenant_minParameter, str_charge_tenant_maxParameter, bit_is_consolidate_zoneParameter, bit_is_printParameter, bit_is_fileParameter, int_typeParameter, str_emailParameter, int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_update_tenant_contract(Nullable<int> int_contract_id, Nullable<System.DateTime> s_date, Nullable<System.DateTime> e_date)
        {
            var int_contract_idParameter = int_contract_id.HasValue ?
                new ObjectParameter("int_contract_id", int_contract_id) :
                new ObjectParameter("int_contract_id", typeof(int));
    
            var s_dateParameter = s_date.HasValue ?
                new ObjectParameter("s_date", s_date) :
                new ObjectParameter("s_date", typeof(System.DateTime));
    
            var e_dateParameter = e_date.HasValue ?
                new ObjectParameter("e_date", e_date) :
                new ObjectParameter("e_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_update_tenant_contract", int_contract_idParameter, s_dateParameter, e_dateParameter);
        }
    
        public virtual int usp_update_tenant_meter(Nullable<int> int_id, Nullable<int> int_tenant_id, string str_meter_id, ObjectParameter int_val)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var str_meter_idParameter = str_meter_id != null ?
                new ObjectParameter("str_meter_id", str_meter_id) :
                new ObjectParameter("str_meter_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_tenant_meter", int_idParameter, int_tenant_idParameter, str_meter_idParameter, int_val);
        }
    
        public virtual int usp_update_tenant_setting(Nullable<int> int_id, Nullable<int> int_tenant_id, Nullable<decimal> dec_demanda_facturable, Nullable<decimal> dec_total_ene)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var dec_demanda_facturableParameter = dec_demanda_facturable.HasValue ?
                new ObjectParameter("dec_demanda_facturable", dec_demanda_facturable) :
                new ObjectParameter("dec_demanda_facturable", typeof(decimal));
    
            var dec_total_eneParameter = dec_total_ene.HasValue ?
                new ObjectParameter("dec_total_ene", dec_total_ene) :
                new ObjectParameter("dec_total_ene", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_tenant_setting", int_idParameter, int_tenant_idParameter, dec_demanda_facturableParameter, dec_total_eneParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_update_user(Nullable<int> int_id, string str_comp_name, string str_contact_name, string str_add_1, string str_add_2, string str_city, string str_state, Nullable<int> int_pin_code, string str_country, string str_email, Nullable<int> int_user_type_id, string str_user_name, string str_password, Nullable<int> int_pm_id, Nullable<int> int_invoice_period)
        {
            var int_idParameter = int_id.HasValue ?
                new ObjectParameter("int_id", int_id) :
                new ObjectParameter("int_id", typeof(int));
    
            var str_comp_nameParameter = str_comp_name != null ?
                new ObjectParameter("str_comp_name", str_comp_name) :
                new ObjectParameter("str_comp_name", typeof(string));
    
            var str_contact_nameParameter = str_contact_name != null ?
                new ObjectParameter("str_contact_name", str_contact_name) :
                new ObjectParameter("str_contact_name", typeof(string));
    
            var str_add_1Parameter = str_add_1 != null ?
                new ObjectParameter("str_add_1", str_add_1) :
                new ObjectParameter("str_add_1", typeof(string));
    
            var str_add_2Parameter = str_add_2 != null ?
                new ObjectParameter("str_add_2", str_add_2) :
                new ObjectParameter("str_add_2", typeof(string));
    
            var str_cityParameter = str_city != null ?
                new ObjectParameter("str_city", str_city) :
                new ObjectParameter("str_city", typeof(string));
    
            var str_stateParameter = str_state != null ?
                new ObjectParameter("str_state", str_state) :
                new ObjectParameter("str_state", typeof(string));
    
            var int_pin_codeParameter = int_pin_code.HasValue ?
                new ObjectParameter("int_pin_code", int_pin_code) :
                new ObjectParameter("int_pin_code", typeof(int));
    
            var str_countryParameter = str_country != null ?
                new ObjectParameter("str_country", str_country) :
                new ObjectParameter("str_country", typeof(string));
    
            var str_emailParameter = str_email != null ?
                new ObjectParameter("str_email", str_email) :
                new ObjectParameter("str_email", typeof(string));
    
            var int_user_type_idParameter = int_user_type_id.HasValue ?
                new ObjectParameter("int_user_type_id", int_user_type_id) :
                new ObjectParameter("int_user_type_id", typeof(int));
    
            var str_user_nameParameter = str_user_name != null ?
                new ObjectParameter("str_user_name", str_user_name) :
                new ObjectParameter("str_user_name", typeof(string));
    
            var str_passwordParameter = str_password != null ?
                new ObjectParameter("str_password", str_password) :
                new ObjectParameter("str_password", typeof(string));
    
            var int_pm_idParameter = int_pm_id.HasValue ?
                new ObjectParameter("int_pm_id", int_pm_id) :
                new ObjectParameter("int_pm_id", typeof(int));
    
            var int_invoice_periodParameter = int_invoice_period.HasValue ?
                new ObjectParameter("int_invoice_period", int_invoice_period) :
                new ObjectParameter("int_invoice_period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_update_user", int_idParameter, str_comp_nameParameter, str_contact_nameParameter, str_add_1Parameter, str_add_2Parameter, str_cityParameter, str_stateParameter, int_pin_codeParameter, str_countryParameter, str_emailParameter, int_user_type_idParameter, str_user_nameParameter, str_passwordParameter, int_pm_idParameter, int_invoice_periodParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_update_tenant_billing_info_rates(Nullable<int> int_tenant_id, Nullable<decimal> dec_rate, Nullable<decimal> dec_seasonal_multi_rate, Nullable<decimal> dec_surcharge_amt)
        {
            var int_tenant_idParameter = int_tenant_id.HasValue ?
                new ObjectParameter("int_tenant_id", int_tenant_id) :
                new ObjectParameter("int_tenant_id", typeof(int));
    
            var dec_rateParameter = dec_rate.HasValue ?
                new ObjectParameter("dec_rate", dec_rate) :
                new ObjectParameter("dec_rate", typeof(decimal));
    
            var dec_seasonal_multi_rateParameter = dec_seasonal_multi_rate.HasValue ?
                new ObjectParameter("dec_seasonal_multi_rate", dec_seasonal_multi_rate) :
                new ObjectParameter("dec_seasonal_multi_rate", typeof(decimal));
    
            var dec_surcharge_amtParameter = dec_surcharge_amt.HasValue ?
                new ObjectParameter("dec_surcharge_amt", dec_surcharge_amt) :
                new ObjectParameter("dec_surcharge_amt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_update_tenant_billing_info_rates", int_tenant_idParameter, dec_rateParameter, dec_seasonal_multi_rateParameter, dec_surcharge_amtParameter);
        }
    
        public virtual int getLastMeterReading(string meterName, Nullable<System.DateTime> monthDate, ObjectParameter lastMeterReading)
        {
            var meterNameParameter = meterName != null ?
                new ObjectParameter("meterName", meterName) :
                new ObjectParameter("meterName", typeof(string));
    
            var monthDateParameter = monthDate.HasValue ?
                new ObjectParameter("monthDate", monthDate) :
                new ObjectParameter("monthDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getLastMeterReading", meterNameParameter, monthDateParameter, lastMeterReading);
        }
    
        public virtual ObjectResult<spProcEnergyLog_Result> spProcEnergyLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spProcEnergyLog_Result>("spProcEnergyLog");
        }
    
        public virtual ObjectResult<Nullable<decimal>> usp_get_meter_reading_new(string tb_name, Nullable<System.DateTime> start_date, Nullable<System.DateTime> end_date)
        {
            var tb_nameParameter = tb_name != null ?
                new ObjectParameter("tb_name", tb_name) :
                new ObjectParameter("tb_name", typeof(string));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("usp_get_meter_reading_new", tb_nameParameter, start_dateParameter, end_dateParameter);
        }
    }
}
