//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDI
    {
        public string id_medidor { get; set; }
        public string CFE_MeterID { get; set; }
        public string tipo_lectura { get; set; }
        public string valor { get; set; }
        public System.DateTime fecha_ocurrencia { get; set; }
    }
}
