//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TenantMNG.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string add_new {
            get {
                return ResourceManager.GetString("add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        public static string alarm {
            get {
                return ResourceManager.GetString("alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Meter.
        /// </summary>
        public static string assign_meter {
            get {
                return ResourceManager.GetString("assign_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign / Detelet Meter.
        /// </summary>
        public static string assign_or_delete_meter {
            get {
                return ResourceManager.GetString("assign_or_delete_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to.
        /// </summary>
        public static string assign_to {
            get {
                return ResourceManager.GetString("assign_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string back_login {
            get {
                return ResourceManager.GetString("back_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Time.
        /// </summary>
        public static string base_time {
            get {
                return ResourceManager.GetString("base_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demanda Facturable.
        /// </summary>
        public static string begin_on {
            get {
                return ResourceManager.GetString("begin_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing adjustment.
        /// </summary>
        public static string bill_adjust {
            get {
                return ResourceManager.GetString("bill_adjust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Period.
        /// </summary>
        public static string bill_period {
            get {
                return ResourceManager.GetString("bill_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule.
        /// </summary>
        public static string bill_rule {
            get {
                return ResourceManager.GetString("bill_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Details.
        /// </summary>
        public static string billing_details {
            get {
                return ResourceManager.GetString("billing_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string capacidad {
            get {
                return ResourceManager.GetString("capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Capacity rate.
        /// </summary>
        public static string capacidad_enter_amount {
            get {
                return ResourceManager.GetString("capacidad_enter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Cenace amount.
        /// </summary>
        public static string cencace_enter_amount {
            get {
                return ResourceManager.GetString("cencace_enter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string changepassword {
            get {
                return ResourceManager.GetString("changepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption Chart.
        /// </summary>
        public static string charts {
            get {
                return ResourceManager.GetString("charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidate zones in bill (this is bill only once even if multiple zones are in overide).
        /// </summary>
        public static string consol_mess {
            get {
                return ResourceManager.GetString("consol_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string contact_details {
            get {
                return ResourceManager.GetString("contact_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Details.
        /// </summary>
        public static string contract_details {
            get {
                return ResourceManager.GetString("contract_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRE related services.
        /// </summary>
        public static string cre_servicios_conexos {
            get {
                return ResourceManager.GetString("cre_servicios_conexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoices.
        /// </summary>
        public static string create_invoices {
            get {
                return ResourceManager.GetString("create_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Invoice.
        /// </summary>
        public static string create_multi {
            get {
                return ResourceManager.GetString("create_multi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Single Invoice.
        /// </summary>
        public static string create_single {
            get {
                return ResourceManager.GetString("create_single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Readings Report.
        /// </summary>
        public static string current_meter_readings_report {
            get {
                return ResourceManager.GetString("current_meter_readings_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Charges.
        /// </summary>
        public static string cust_energy {
            get {
                return ResourceManager.GetString("cust_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string date_e_bill_date {
            get {
                return ResourceManager.GetString("date_e_bill_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Pay Date.
        /// </summary>
        public static string date_pay_date {
            get {
                return ResourceManager.GetString("date_pay_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string date_s_bill_date {
            get {
                return ResourceManager.GetString("date_s_bill_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of Week.
        /// </summary>
        public static string day_of_week {
            get {
                return ResourceManager.GetString("day_of_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 Days.
        /// </summary>
        public static string day15 {
            get {
                return ResourceManager.GetString("day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Energy.
        /// </summary>
        public static string dec_base_energy {
            get {
                return ResourceManager.GetString("dec_base_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Energy Rate.
        /// </summary>
        public static string dec_base_rate {
            get {
                return ResourceManager.GetString("dec_base_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Intermediate Energy.
        /// </summary>
        public static string dec_current_inter_energy {
            get {
                return ResourceManager.GetString("dec_current_inter_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Peack Energy.
        /// </summary>
        public static string dec_current_peak_energy {
            get {
                return ResourceManager.GetString("dec_current_peak_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Charges.
        /// </summary>
        public static string dec_custome_charges {
            get {
                return ResourceManager.GetString("dec_custome_charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand (kW).
        /// </summary>
        public static string dec_demad {
            get {
                return ResourceManager.GetString("dec_demad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Facturable Amount.
        /// </summary>
        public static string dec_demanda_facturable_amount {
            get {
                return ResourceManager.GetString("dec_demanda_facturable_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Energy.
        /// </summary>
        public static string dec_inter_energy {
            get {
                return ResourceManager.GetString("dec_inter_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Energy Rate.
        /// </summary>
        public static string dec_inter_energy_rate {
            get {
                return ResourceManager.GetString("dec_inter_energy_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peack Energy.
        /// </summary>
        public static string dec_peak_energy {
            get {
                return ResourceManager.GetString("dec_peak_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peack Energy Rate.
        /// </summary>
        public static string dec_peak_energy_rate {
            get {
                return ResourceManager.GetString("dec_peak_energy_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Intermediate Energy.
        /// </summary>
        public static string dec_prev_inter_energy {
            get {
                return ResourceManager.GetString("dec_prev_inter_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Peack Energy.
        /// </summary>
        public static string dec_prev_peak_energy {
            get {
                return ResourceManager.GetString("dec_prev_peak_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Energy Rate.
        /// </summary>
        public static string dec_rate {
            get {
                return ResourceManager.GetString("dec_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Demand Rate.
        /// </summary>
        public static string dec_seasonal_multi_rate {
            get {
                return ResourceManager.GetString("dec_seasonal_multi_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Demand Rate.
        /// </summary>
        public static string dec_surcharge_amt {
            get {
                return ResourceManager.GetString("dec_surcharge_amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        public static string dec_tax_amt {
            get {
                return ResourceManager.GetString("dec_tax_amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string dec_total {
            get {
                return ResourceManager.GetString("dec_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Energy.
        /// </summary>
        public static string dec_total_ene {
            get {
                return ResourceManager.GetString("dec_total_ene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand.
        /// </summary>
        public static string demand {
            get {
                return ResourceManager.GetString("demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable Demand Rate.
        /// </summary>
        public static string demand_fact {
            get {
                return ResourceManager.GetString("demand_fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Demand.
        /// </summary>
        public static string demanda_base {
            get {
                return ResourceManager.GetString("demanda_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Demand.
        /// </summary>
        public static string demanda_intermedia {
            get {
                return ResourceManager.GetString("demanda_intermedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Demand.
        /// </summary>
        public static string demanda_punta {
            get {
                return ResourceManager.GetString("demanda_punta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        public static string detach {
            get {
                return ResourceManager.GetString("detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach Meter.
        /// </summary>
        public static string detach_meter {
            get {
                return ResourceManager.GetString("detach_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution $kW.
        /// </summary>
        public static string distribucion {
            get {
                return ResourceManager.GetString("distribucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution $kW.
        /// </summary>
        public static string distribución {
            get {
                return ResourceManager.GetString("distribución", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the distribution amount.
        /// </summary>
        public static string distribucion_enter_amount {
            get {
                return ResourceManager.GetString("distribucion_enter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string e_date {
            get {
                return ResourceManager.GetString("e_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bill Rate.
        /// </summary>
        public static string edit_bill_rate {
            get {
                return ResourceManager.GetString("edit_bill_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración de Email.
        /// </summary>
        public static string email_setup {
            get {
                return ResourceManager.GetString("email_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending on.
        /// </summary>
        public static string end_on {
            get {
                return ResourceManager.GetString("end_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Energy.
        /// </summary>
        public static string energia_activa {
            get {
                return ResourceManager.GetString("energia_activa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactive Energy.
        /// </summary>
        public static string energia_reactiva {
            get {
                return ResourceManager.GetString("energia_reactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string energy {
            get {
                return ResourceManager.GetString("energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Energy Management.
        /// </summary>
        public static string EnergyManagement {
            get {
                return ResourceManager.GetString("EnergyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy Management One.
        /// </summary>
        public static string EnergyManagementOne {
            get {
                return ResourceManager.GetString("EnergyManagementOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string export_to_excel {
            get {
                return ResourceManager.GetString("export_to_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount.
        /// </summary>
        public static string final_amout {
            get {
                return ResourceManager.GetString("final_amout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET.
        /// </summary>
        public static string get {
            get {
                return ResourceManager.GetString("get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Much Energy I consume.
        /// </summary>
        public static string how_much {
            get {
                return ResourceManager.GetString("how_much", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string int_pin_code {
            get {
                return ResourceManager.GetString("int_pin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Template.
        /// </summary>
        public static string int_template_id {
            get {
                return ResourceManager.GetString("int_template_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string int_tenant_id {
            get {
                return ResourceManager.GetString("int_tenant_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Demand Rate.
        /// </summary>
        public static string inter_demand_rate {
            get {
                return ResourceManager.GetString("inter_demand_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Energy.
        /// </summary>
        public static string inter_energy {
            get {
                return ResourceManager.GetString("inter_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter Time.
        /// </summary>
        public static string inter_time {
            get {
                return ResourceManager.GetString("inter_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving invoice. Please try again later.
        /// </summary>
        public static string invoce_failure {
            get {
                return ResourceManager.GetString("invoce_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invocie List.
        /// </summary>
        public static string invocie_list {
            get {
                return ResourceManager.GetString("invocie_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice was saved successfully.
        /// </summary>
        public static string invoice_success {
            get {
                return ResourceManager.GetString("invoice_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string lock_out {
            get {
                return ResourceManager.GetString("lock_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost password?.
        /// </summary>
        public static string lost_password {
            get {
                return ResourceManager.GetString("lost_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string manager {
            get {
                return ResourceManager.GetString("manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string meter {
            get {
                return ResourceManager.GetString("meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this meter is already assign to another tenant..
        /// </summary>
        public static string meter_assign_mess_alredy {
            get {
                return ResourceManager.GetString("meter_assign_mess_alredy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there may be problem in saving data.please try again later..
        /// </summary>
        public static string meter_assign_mess_fail {
            get {
                return ResourceManager.GetString("meter_assign_mess_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter assign to tenant successfully..
        /// </summary>
        public static string meter_assign_mess_succ {
            get {
                return ResourceManager.GetString("meter_assign_mess_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Detach.
        /// </summary>
        public static string meter_detch {
            get {
                return ResourceManager.GetString("meter_detch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Meters.
        /// </summary>
        public static string meter_list {
            get {
                return ResourceManager.GetString("meter_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Name.
        /// </summary>
        public static string meter_name {
            get {
                return ResourceManager.GetString("meter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Update.
        /// </summary>
        public static string meter_update {
            get {
                return ResourceManager.GetString("meter_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon To Fri.
        /// </summary>
        public static string mon_to_fri {
            get {
                return ResourceManager.GetString("mon_to_fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string monthly {
            get {
                return ResourceManager.GetString("monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Information Inserted Successfully..
        /// </summary>
        public static string msg_bill_info_success {
            get {
                return ResourceManager.GetString("msg_bill_info_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Rates are updated successfully..
        /// </summary>
        public static string msg_bill_rate_success {
            get {
                return ResourceManager.GetString("msg_bill_rate_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is updated successfully.
        /// </summary>
        public static string msg_change_pass_success {
            get {
                return ResourceManager.GetString("msg_change_pass_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there may be problem in saving data.please try again later..
        /// </summary>
        public static string msg_global_fail {
            get {
                return ResourceManager.GetString("msg_global_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details save successfully..
        /// </summary>
        public static string msg_global_success {
            get {
                return ResourceManager.GetString("msg_global_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry !! Invalid Login..
        /// </summary>
        public static string msg_invalid_login {
            get {
                return ResourceManager.GetString("msg_invalid_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry !! Licensing for this product has expired..
        /// </summary>
        public static string msg_licencse {
            get {
                return ResourceManager.GetString("msg_licencse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later.
        /// </summary>
        public static string msg_lock_out {
            get {
                return ResourceManager.GetString("msg_lock_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Invoice generated successfully..
        /// </summary>
        public static string msg_multi_invocie {
            get {
                return ResourceManager.GetString("msg_multi_invocie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, still no contract start for this tenant..
        /// </summary>
        public static string msg_no_contract {
            get {
                return ResourceManager.GetString("msg_no_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this username/email not found into the system..
        /// </summary>
        public static string msg_password_fail {
            get {
                return ResourceManager.GetString("msg_password_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Send to your email address..
        /// </summary>
        public static string msg_password_success {
            get {
                return ResourceManager.GetString("msg_password_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is updated successfully..
        /// </summary>
        public static string msg_profile_update {
            get {
                return ResourceManager.GetString("msg_profile_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information Inserted Successfully..
        /// </summary>
        public static string msg_save_contact_success {
            get {
                return ResourceManager.GetString("msg_save_contact_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Information Inserted Successfully..
        /// </summary>
        public static string msg_save_contract_success {
            get {
                return ResourceManager.GetString("msg_save_contract_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Setup Inserted Successfully..
        /// </summary>
        public static string msg_save_email_success {
            get {
                return ResourceManager.GetString("msg_save_email_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Inserted Successfully..
        /// </summary>
        public static string msg_save_setting {
            get {
                return ResourceManager.GetString("msg_save_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, still no contract start for this tenant..
        /// </summary>
        public static string no_contract_mess {
            get {
                return ResourceManager.GetString("no_contract_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not assign.
        /// </summary>
        public static string not_assign {
            get {
                return ResourceManager.GetString("not_assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CENACE Operating Rate.
        /// </summary>
        public static string operacion_cenace {
            get {
                return ResourceManager.GetString("operacion_cenace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string passplace {
            get {
                return ResourceManager.GetString("passplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Require.
        /// </summary>
        public static string passrequire {
            get {
                return ResourceManager.GetString("passrequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Date.
        /// </summary>
        public static string pay_date {
            get {
                return ResourceManager.GetString("pay_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Demand Rate.
        /// </summary>
        public static string peak_demand_rate {
            get {
                return ResourceManager.GetString("peak_demand_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peack Energy.
        /// </summary>
        public static string peak_energy {
            get {
                return ResourceManager.GetString("peak_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Time.
        /// </summary>
        public static string peak_time {
            get {
                return ResourceManager.GetString("peak_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code.
        /// </summary>
        public static string pin_code {
            get {
                return ResourceManager.GetString("pin_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM List.
        /// </summary>
        public static string pm_list {
            get {
                return ResourceManager.GetString("pm_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Manager List.
        /// </summary>
        public static string pm_list_title {
            get {
                return ResourceManager.GetString("pm_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM List.
        /// </summary>
        public static string pmuser {
            get {
                return ResourceManager.GetString("pmuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for Capacity.
        /// </summary>
        public static string precio_capacidad {
            get {
                return ResourceManager.GetString("precio_capacidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for CENACE .
        /// </summary>
        public static string precio_cenace {
            get {
                return ResourceManager.GetString("precio_cenace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price por SCnMEM.
        /// </summary>
        public static string precio_cre_servicios_conexos {
            get {
                return ResourceManager.GetString("precio_cre_servicios_conexos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Bonus of F of P..
        /// </summary>
        public static string precio_decuento_bonificacion {
            get {
                return ResourceManager.GetString("precio_decuento_bonificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for Distribution.
        /// </summary>
        public static string precio_distribucion {
            get {
                return ResourceManager.GetString("precio_distribucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2% for low voltage measurement.
        /// </summary>
        public static string precio_dos_porciento_baja_tension {
            get {
                return ResourceManager.GetString("precio_dos_porciento_baja_tension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for Energy.
        /// </summary>
        public static string precio_energia {
            get {
                return ResourceManager.GetString("precio_energia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for Supply.
        /// </summary>
        public static string precio_suministro {
            get {
                return ResourceManager.GetString("precio_suministro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for Transmission.
        /// </summary>
        public static string precio_transmision {
            get {
                return ResourceManager.GetString("precio_transmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Invoice Chart.
        /// </summary>
        public static string prev_chart {
            get {
                return ResourceManager.GetString("prev_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        public static string property {
            get {
                return ResourceManager.GetString("property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Meter.
        /// </summary>
        public static string reassign_meter {
            get {
                return ResourceManager.GetString("reassign_meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string recover {
            get {
                return ResourceManager.GetString("recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string s_date {
            get {
                return ResourceManager.GetString("s_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string sat {
            get {
                return ResourceManager.GetString("sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Information.
        /// </summary>
        public static string save_info {
            get {
                return ResourceManager.GetString("save_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Tenant.
        /// </summary>
        public static string search_by_tenant {
            get {
                return ResourceManager.GetString("search_by_tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Tenant.
        /// </summary>
        public static string search_tenant {
            get {
                return ResourceManager.GetString("search_tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Billing Period.
        /// </summary>
        public static string select_bill {
            get {
                return ResourceManager.GetString("select_bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Option for.
        /// </summary>
        public static string select_option {
            get {
                return ResourceManager.GetString("select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Property Manager.
        /// </summary>
        public static string select_pm {
            get {
                return ResourceManager.GetString("select_pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Connected Services rate.
        /// </summary>
        public static string servicios_conexos_enter_amount {
            get {
                return ResourceManager.GetString("servicios_conexos_enter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Rate Hours.
        /// </summary>
        public static string set_energy_hours {
            get {
                return ResourceManager.GetString("set_energy_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Hours.
        /// </summary>
        public static string set_hours {
            get {
                return ResourceManager.GetString("set_hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry !! no data found.
        /// </summary>
        public static string sorry_mess {
            get {
                return ResourceManager.GetString("sorry_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 1.
        /// </summary>
        public static string str_add_1 {
            get {
                return ResourceManager.GetString("str_add_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        public static string str_add_2 {
            get {
                return ResourceManager.GetString("str_add_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BCC Email Address.
        /// </summary>
        public static string str_bcc_email {
            get {
                return ResourceManager.GetString("str_bcc_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text.
        /// </summary>
        public static string str_body {
            get {
                return ResourceManager.GetString("str_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Email Address.
        /// </summary>
        public static string str_cc_email {
            get {
                return ResourceManager.GetString("str_cc_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge tenant for a maximum of.
        /// </summary>
        public static string str_charge_tenant_max {
            get {
                return ResourceManager.GetString("str_charge_tenant_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge tenant for a minimum of.
        /// </summary>
        public static string str_charge_tenant_min {
            get {
                return ResourceManager.GetString("str_charge_tenant_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string str_city {
            get {
                return ResourceManager.GetString("str_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string str_comp_name {
            get {
                return ResourceManager.GetString("str_comp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string str_contact_name {
            get {
                return ResourceManager.GetString("str_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string str_country {
            get {
                return ResourceManager.GetString("str_country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string str_custome_charge_desc {
            get {
                return ResourceManager.GetString("str_custome_charge_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string str_email {
            get {
                return ResourceManager.GetString("str_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Email Address.
        /// </summary>
        public static string str_from_email {
            get {
                return ResourceManager.GetString("str_from_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum billable override event.
        /// </summary>
        public static string str_min_billable_over {
            get {
                return ResourceManager.GetString("str_min_billable_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string str_new_password {
            get {
                return ResourceManager.GetString("str_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string str_password {
            get {
                return ResourceManager.GetString("str_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string str_state {
            get {
                return ResourceManager.GetString("str_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Text.
        /// </summary>
        public static string str_subject {
            get {
                return ResourceManager.GetString("str_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string str_user_name {
            get {
                return ResourceManager.GetString("str_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply (Operating Rate).
        /// </summary>
        public static string suministro {
            get {
                return ResourceManager.GetString("suministro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please entrer the supply amount .
        /// </summary>
        public static string suministro_enter_amount {
            get {
                return ResourceManager.GetString("suministro_enter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string sun {
            get {
                return ResourceManager.GetString("sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmition Rate.
        /// </summary>
        public static string tarifa_transmision {
            get {
                return ResourceManager.GetString("tarifa_transmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Status.
        /// </summary>
        public static string teant_status {
            get {
                return ResourceManager.GetString("teant_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        public static string tenant {
            get {
                return ResourceManager.GetString("tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Activity Log.
        /// </summary>
        public static string tenant_actitivy_log {
            get {
                return ResourceManager.GetString("tenant_actitivy_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant consumption Report.
        /// </summary>
        public static string tenant_consumption_report {
            get {
                return ResourceManager.GetString("tenant_consumption_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Invoice List.
        /// </summary>
        public static string tenant_inv_list {
            get {
                return ResourceManager.GetString("tenant_inv_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant List.
        /// </summary>
        public static string tenant_list {
            get {
                return ResourceManager.GetString("tenant_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Energy Consumption.
        /// </summary>
        public static string tenantEngcon {
            get {
                return ResourceManager.GetString("tenantEngcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant User.
        /// </summary>
        public static string tenantuser {
            get {
                return ResourceManager.GetString("tenantuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMESTAMP.
        /// </summary>
        public static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your e-mail address below and we will send you instructions how to recover a password..
        /// </summary>
        public static string title_password {
            get {
                return ResourceManager.GetString("title_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string total_amt {
            get {
                return ResourceManager.GetString("total_amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Energy.
        /// </summary>
        public static string total_energy {
            get {
                return ResourceManager.GetString("total_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the transmition amount.
        /// </summary>
        public static string transmision_enter_amount {
            get {
                return ResourceManager.GetString("transmision_enter_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Require.
        /// </summary>
        public static string unamerequire {
            get {
                return ResourceManager.GetString("unamerequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User Name.
        /// </summary>
        public static string usernamplace {
            get {
                return ResourceManager.GetString("usernamplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Surchage Amount.
        /// </summary>
        public static string val_enter_amt {
            get {
                return ResourceManager.GetString("val_enter_amt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Billing Rate.
        /// </summary>
        public static string val_enter_bill_rate {
            get {
                return ResourceManager.GetString("val_enter_bill_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Company Name.
        /// </summary>
        public static string val_enter_cmp_name {
            get {
                return ResourceManager.GetString("val_enter_cmp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Contact Name.
        /// </summary>
        public static string val_enter_contact_name {
            get {
                return ResourceManager.GetString("val_enter_contact_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter End Date.
        /// </summary>
        public static string val_enter_e_date {
            get {
                return ResourceManager.GetString("val_enter_e_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Email.
        /// </summary>
        public static string val_enter_email {
            get {
                return ResourceManager.GetString("val_enter_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter From Date.
        /// </summary>
        public static string val_enter_from_date {
            get {
                return ResourceManager.GetString("val_enter_from_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Message Text..
        /// </summary>
        public static string val_enter_message {
            get {
                return ResourceManager.GetString("val_enter_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter New Password.
        /// </summary>
        public static string val_enter_new_pass {
            get {
                return ResourceManager.GetString("val_enter_new_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Password.
        /// </summary>
        public static string val_enter_pass {
            get {
                return ResourceManager.GetString("val_enter_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Pay Date.
        /// </summary>
        public static string val_enter_pay_date {
            get {
                return ResourceManager.GetString("val_enter_pay_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Start Date.
        /// </summary>
        public static string val_enter_s_date {
            get {
                return ResourceManager.GetString("val_enter_s_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter subject.
        /// </summary>
        public static string val_enter_sub {
            get {
                return ResourceManager.GetString("val_enter_sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Template.
        /// </summary>
        public static string val_enter_template {
            get {
                return ResourceManager.GetString("val_enter_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Time.
        /// </summary>
        public static string val_enter_time {
            get {
                return ResourceManager.GetString("val_enter_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter To Date.
        /// </summary>
        public static string val_enter_to_date {
            get {
                return ResourceManager.GetString("val_enter_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User Name.
        /// </summary>
        public static string val_enter_uname {
            get {
                return ResourceManager.GetString("val_enter_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Value..
        /// </summary>
        public static string val_enter_val {
            get {
                return ResourceManager.GetString("val_enter_val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter form email..
        /// </summary>
        public static string val_form_email {
            get {
                return ResourceManager.GetString("val_form_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string val_invalid_email {
            get {
                return ResourceManager.GetString("val_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Time in hh:mm format.
        /// </summary>
        public static string val_invalid_time {
            get {
                return ResourceManager.GetString("val_invalid_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen password should meet the following criteria - Min 8 characters - atleast 1 Alphabet, 1 Number and 1 Special Character.
        /// </summary>
        public static string val_pass {
            get {
                return ResourceManager.GetString("val_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username should meet the following criteria one letter,one number and minimum of eight (8) characters.
        /// </summary>
        public static string val_uname {
            get {
                return ResourceManager.GetString("val_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnergyConsumed.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        public static string view_all {
            get {
                return ResourceManager.GetString("view_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to detach this meter from this tenant ?.
        /// </summary>
        public static string war_detch_mess {
            get {
                return ResourceManager.GetString("war_detch_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string weekly {
            get {
                return ResourceManager.GetString("weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you like to do ?.
        /// </summary>
        public static string what_like_to_do {
            get {
                return ResourceManager.GetString("what_like_to_do", resourceCulture);
            }
        }
    }
}
