//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_TYPE_MAP
    {
        public int ID { get; set; }
        public string ID_ { get; set; }
        public string TIMEZONE { get; set; }
        public string RECORDTYPE { get; set; }
        public string VALUEFACETS { get; set; }
        public string TABLE_NAME { get; set; }
        public string DB_TIMEZONE { get; set; }
    }
}
