//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NiagaraEntities : DbContext
    {
        public NiagaraEntities()
            : base("name=NiagaraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AMETEC_POINTS_CONSUMOKWH_CFG0> AMETEC_POINTS_CONSUMOKWH_CFG0 { get; set; }
        public virtual DbSet<AMETEC_POINTS_CONSUMOKWH1_CFG0> AMETEC_POINTS_CONSUMOKWH1_CFG0 { get; set; }
        public virtual DbSet<AMETEC_POINTS_CONSUMOKWH2_CFG0> AMETEC_POINTS_CONSUMOKWH2_CFG0 { get; set; }
        public virtual DbSet<AMETEC_POINTS_CONSUMOKWH3_CFG0> AMETEC_POINTS_CONSUMOKWH3_CFG0 { get; set; }
        public virtual DbSet<AMETEC_SUBMETERING_TOTAL> AMETEC_SUBMETERING_TOTAL { get; set; }
        public virtual DbSet<AMETEC_SUBMETERING_TOTAL1> AMETEC_SUBMETERING_TOTAL1 { get; set; }
        public virtual DbSet<AMETEC_SUBMETERING_TOTAL2> AMETEC_SUBMETERING_TOTAL2 { get; set; }
        public virtual DbSet<AMETEC_SUBMETERING_TOTAL3> AMETEC_SUBMETERING_TOTAL3 { get; set; }
        public virtual DbSet<AMETEC_SUBMETERING_TOTAL5> AMETEC_SUBMETERING_TOTAL5 { get; set; }
        public virtual DbSet<AMETEC_SUBMETERING_TOTALPLANTPOWER> AMETEC_SUBMETERING_TOTALPLANTPOWER { get; set; }
        public virtual DbSet<HISTORY_CONFIG> HISTORY_CONFIG { get; set; }
        public virtual DbSet<HISTORY_TYPE_MAP> HISTORY_TYPE_MAP { get; set; }
        public virtual DbSet<HISTORYNUMERICTRENDRECORD> HISTORYNUMERICTRENDRECORDs { get; set; }
        public virtual DbSet<ProEnergyLog> GetEnergy { get; set; }


      
    }
}
