//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pm_billing_hours
    {
        public int int_rate_id { get; set; }
        public Nullable<int> int_pm_id { get; set; }
        public string str_peak_s_time_m { get; set; }
        public string str_peak_e_time_m { get; set; }
        public string str_inter_s_time_1_m { get; set; }
        public string str_inter_e_time_1_m { get; set; }
        public string str_inter_s_time_2_m { get; set; }
        public string str_inter_e_time_2_m { get; set; }
        public string str_base_s_time_m { get; set; }
        public string str_base_e_time_m { get; set; }
        public string str_base_s_time_sat { get; set; }
        public string str_base_e_time_sat { get; set; }
        public string str_inter_s_time_sat { get; set; }
        public string str_inter_e_time_sat { get; set; }
        public string str_base_s_time_sun { get; set; }
        public string str_base_e_time_sun { get; set; }
        public string str_inter_s_time_sun { get; set; }
        public string str_inter_e_time_sun { get; set; }
    
        public virtual tbl_user_master tbl_user_master { get; set; }
    }
}
