//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user_master()
        {
            this.tbl_tenant_email_setup = new HashSet<tbl_tenant_email_setup>();
            this.tbl_tenant_meter = new HashSet<tbl_tenant_meter>();
            this.tbl_tenant_billing_info = new HashSet<tbl_tenant_billing_info>();
            this.tbl_tenant_contract = new HashSet<tbl_tenant_contract>();
            this.tbl_pm_billing_hours = new HashSet<tbl_pm_billing_hours>();
            this.tbl_tenant_settings = new HashSet<tbl_tenant_settings>();
            this.tbl_invoice = new HashSet<tbl_invoice>();
        }
    
        public int int_id { get; set; }
        public string str_comp_name { get; set; }
        public string str_contact_name { get; set; }
        public string str_add_1 { get; set; }
        public string str_add_2 { get; set; }
        public string str_city { get; set; }
        public string str_state { get; set; }
        public Nullable<int> int_pin_code { get; set; }
        public string str_country { get; set; }
        public Nullable<int> int_user_type_id { get; set; }
        public string str_user_name { get; set; }
        public string str_password { get; set; }
        public Nullable<int> int_pm_id { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string str_email { get; set; }
        public Nullable<decimal> dec_last_peak_energy { get; set; }
        public Nullable<decimal> dec_last_inter_energy { get; set; }
        public Nullable<int> int_invoice_period { get; set; }
    
        public virtual tbl_user_type tbl_user_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tenant_email_setup> tbl_tenant_email_setup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tenant_meter> tbl_tenant_meter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tenant_billing_info> tbl_tenant_billing_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tenant_contract> tbl_tenant_contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pm_billing_hours> tbl_pm_billing_hours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_tenant_settings> tbl_tenant_settings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
    }
}
