//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenantMNG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_zone_master
    {
        public int int_zone_id { get; set; }
        public string str_description { get; set; }
        public string str_override { get; set; }
        public Nullable<bool> bit_status { get; set; }
    }
}
